/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionBenevole;

import gestionbadr.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.apache.log4j.Logger;

public class RechercherBenevole extends javax.swing.JFrame {
static Logger log = Logger.getLogger(RechercherBenevole.class.getName());



    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    char id; // id de l'administrateur pour qu'il revoi au bon HOME
    Statement st = null;
    ResultSet rs = null;

    public RechercherBenevole() {
        
        initComponents();
        //Initialiser_Tableau_Benevole();
        addWindowListener (new WindowAdapter(){
			public void windowClosing (WindowEvent e){
                            Cancel();
			}
		});
    }
    
    public RechercherBenevole(char id) {
        
        initComponents();
        this.id=id;
        //Initialiser_Tableau_Benevole();
        addWindowListener (new WindowAdapter(){
			public void windowClosing (WindowEvent e){
                            Cancel();
			}
		});
    }
    
    private void Cancel(){
         // TODO add your handling code here:
        this.dispose();
        this.setVisible(false);
        Benevole s = new Benevole();
        s.id = id;
        s.setVisible(true);
         addWindowListener (new WindowAdapter(){
			public void windowClosing (WindowEvent e){
                            Cancel();
			}
		});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tBenevole = new javax.swing.JTable(){
            public boolean isCellEditable(int d, int c){
                return false;
            }
        };
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        bRechercherMalade = new javax.swing.JButton();
        cWillayaBenevole = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rechercher Benevole");
        setResizable(false);

        tBenevole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Benevole", "Nom", "Prenom", "Adress", "Ville", "Telephone ", "Email", "Date Naissance", "fonction"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tBenevole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBenevoleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tBenevole);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Malade"));

        jLabel10.setText("Nom :");

        jLabel11.setText("Prenom :");

        bRechercherMalade.setText("Rechercher");
        bRechercherMalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRechercherMaladeActionPerformed(evt);
            }
        });

        cWillayaBenevole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa", "Biskra", "Béchar", "Blida", "Bouira", "Tamanrasset", "Tébessa", "Tlemcen", "Tiaret", "Tizi Ouzou", "Alger", "Djelfa", "Jijel", "Sétif", "Saïda", "Skikda", "Sidi Bel Abbès", "Annaba", "Guelma", "Constantine", "Médéa", "Mostaganem", "M'Sila", "Mascara", "Ouargla", "Oran", "El Bayadh", "Illizi", "Bordj Bou Arreridj", "Boumerdès", "El Tarf", "Tindouf", "Tissemsilt", "El Oued", "Khenchela", "Souk Ahras", "Tipaza", "Mila", "Aïn Defla", "Naàma", "Aïn Témouchent", "Ghardaïa", "Relizane", " " }));
        cWillayaBenevole.setSelectedIndex(-1);

        jLabel8.setText("Willaya :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cWillayaBenevole, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(bRechercherMalade)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cWillayaBenevole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(bRechercherMalade)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(705, 705, 705)
                        .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCancel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(865, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tBenevoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBenevoleMouseClicked
        log.trace("Open Methode tBenevoleMouseClicked ");
        log.debug("Id Admin Avant modification = " + id);
        int row = tBenevole.getSelectedRow();
        String n;
        n = tBenevole.getModel().getValueAt(row, 0).toString();
        try {
            String sql = "SELECT * FROM benevole WHERE id_b = '" + n + "'";
            pst = con.prepareStatement(sql);
            rst = pst.executeQuery(sql);
            if (rst.next()) {
                this.setVisible(false);
                log.debug("Id Admin= " + id);
                Benevole s = new Benevole(id);
                s.setVisible(true);

                String Nom_b = rst.getString("Nom_b");
                s.txtNomb.setText(Nom_b);
                Date date_n_b = rst.getDate("date_n_b");
                s.jDateNaissance.setDate(date_n_b);
                String nom_m = rst.getString("prenom_b");
                s.txtPrenom.setText(nom_m);
                String willaya_b = rst.getString("willaya_b");
                s.cWillayaBenevole.setSelectedItem(willaya_b);
                String tel_famille_m = rst.getString("num_tel_b");
                s.txtNumTelB.setText(tel_famille_m);
                String prenom_m = rst.getString("email_b");
                s.txtEmail.setText(prenom_m);
                String ville_m = rst.getString("fonction");
                s.txtFonction.setText(ville_m);
                String sexe_b = rst.getString("sexe_b");
                s.cSexeB.setSelectedItem(sexe_b);
                s.id_b = rst.getInt("id_b");
                
                s.bModifier.setEnabled(true);
                s.bSave.setEnabled(false);
            }
            log.trace("Close Methode tBenevoleMouseClicked ");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            log.error("Erreur tBenevoleMouseClicked : ", e);
        }
    }//GEN-LAST:event_tBenevoleMouseClicked

    private void bRechercherMaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRechercherMaladeActionPerformed
        con = Connect.connect();
        if ((cWillayaBenevole.getSelectedIndex() == -1) && txtNom.getText().equals("") && txtPrenom.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Une des combinaison suivante:"
                    + "\n     - Nom."
                    + "\n     - Prenom."
                    + "\n     - Willaya."
                    + "\n     - Nom + Prenom.");
        }else if (cWillayaBenevole.getSelectedIndex() == -1 && txtNom.getText().equals("")) {
            try {
                //1er requete pour identifier une erreur de redendence 
                String sql = "Select * from benevole where prenom_b='" + txtPrenom.getText() + "'";

                pst = con.prepareStatement(sql);
                rst = pst.executeQuery(sql);
                tBenevole.setModel(DbUtils.resultSetToTableModel(rst));

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                log.error("Erreur bRechercherMaladeActionPerformed : ", e);
            }
            
        } else if (cWillayaBenevole.getSelectedIndex() == -1 && txtPrenom.getText().equals("")) {
            try {
                //1er requete pour identifier une erreur de redendence 
                String sql = "Select * from benevole where nom_b='" + txtNom.getText() + "'";

                pst = con.prepareStatement(sql);
                rst = pst.executeQuery(sql);
                tBenevole.setModel(DbUtils.resultSetToTableModel(rst));

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                log.error("Erreur bRechercherMaladeActionPerformed : ", e);
            }
            
        } else if (txtNom.getText().equals("") && txtPrenom.getText().equals("")) {
            try {
                //1er requete pour identifier une erreur de redendence 
                String sql = "Select * from benevole where willaya_b='" + cWillayaBenevole.getSelectedItem() + "'";

                pst = con.prepareStatement(sql);
                rst = pst.executeQuery(sql);
                tBenevole.setModel(DbUtils.resultSetToTableModel(rst));

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                log.error("Erreur bRechercherMaladeActionPerformed : ", e);
            }
            
        } else if (cWillayaBenevole.getSelectedIndex() == -1) {
            try {
                //1er requete pour identifier une erreur de redendence 
                String sql = "Select * from benevole where nom_b='" + txtNom.getText()
                        + "' AND prenom_b='" + txtPrenom.getText() + "'";

                pst = con.prepareStatement(sql);
                rst = pst.executeQuery(sql);
                tBenevole.setModel(DbUtils.resultSetToTableModel(rst));

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                log.error("Erreur bRechercherMaladeActionPerformed : ", e);
            }
        } 
    }//GEN-LAST:event_bRechercherMaladeActionPerformed

    private void Initialiser_Tableau_Benevole(){
         DefaultTableModel md = new DefaultTableModel();
        md.setColumnIdentifiers(new String[]{"Nom benevole", "Prenom", "Willaya"});
        try {
            con = Connect.connect();
            st = con.createStatement();
            rs = st.executeQuery("select * from  benevole ");
            while (rs.next()) {
                md.addRow(new Object[]{rs.getObject("nom_b"), rs.getObject("Prenom_b"), rs.getObject("willaya_b")});
            }
            tBenevole.setModel(md);

            setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
       Cancel();
    }//GEN-LAST:event_bCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercherBenevole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercherBenevole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercherBenevole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercherBenevole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RechercherBenevole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bRechercherMalade;
    protected javax.swing.JComboBox cWillayaBenevole;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable tBenevole;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables
}
