/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionbadr;

import GestionConvontion.ConsulterConvontion;
import GestionLoggin.ConsulterUser;
import GestionLoggin.Employer;
import GestionConvontion.Convontion;
import GestionPartenaire.ConsulterPartenaire;
import GestionPartenaire.partenaire;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author FAWZI
 */
public class Parametre extends javax.swing.JFrame {
char id; // id de l'administrateur pour qu'il revoi au bon HOME
    /**
     * Creates new form Parametre
     */
    public Parametre() {
        initComponents();
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                Cancel();
            }
        });
    }
    
    public Parametre(char id) {
        initComponents();
        this.id=id;
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                Cancel();
            }
        });
    }
    
    private void Cancel(){
        this.setVisible(false);
        HomeAdministrateur h = new HomeAdministrateur();
        h.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bAjouterUtilisateur = new javax.swing.JButton();
        bConsulterUtilisateur = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bAjouterPartenaire = new javax.swing.JButton();
        bConsulterPartenaire = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bAjouterConvontion = new javax.swing.JButton();
        bConsulterConvontion = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametre");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des Utilisateurs"));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.setLayout(null);

        bAjouterUtilisateur.setText("Ajouter");
        bAjouterUtilisateur.setBorder(null);
        bAjouterUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjouterUtilisateurActionPerformed(evt);
            }
        });
        jPanel2.add(bAjouterUtilisateur);
        bAjouterUtilisateur.setBounds(20, 30, 160, 40);

        bConsulterUtilisateur.setText("Consulter");
        bConsulterUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsulterUtilisateurActionPerformed(evt);
            }
        });
        jPanel2.add(bConsulterUtilisateur);
        bConsulterUtilisateur.setBounds(20, 80, 160, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des Partenaires"));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.setLayout(null);

        bAjouterPartenaire.setText("Ajouter");
        bAjouterPartenaire.setBorder(null);
        bAjouterPartenaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjouterPartenaireActionPerformed(evt);
            }
        });
        jPanel3.add(bAjouterPartenaire);
        bAjouterPartenaire.setBounds(20, 30, 160, 40);

        bConsulterPartenaire.setText("Consulter");
        bConsulterPartenaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsulterPartenaireActionPerformed(evt);
            }
        });
        jPanel3.add(bConsulterPartenaire);
        bConsulterPartenaire.setBounds(20, 80, 160, 40);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des Convontions"));
        jPanel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.setLayout(null);

        bAjouterConvontion.setText("Ajouter");
        bAjouterConvontion.setBorder(null);
        bAjouterConvontion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjouterConvontionActionPerformed(evt);
            }
        });
        jPanel4.add(bAjouterConvontion);
        bAjouterConvontion.setBounds(20, 30, 160, 40);

        bConsulterConvontion.setText("Consulter");
        bConsulterConvontion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsulterConvontionActionPerformed(evt);
            }
        });
        jPanel4.add(bConsulterConvontion);
        bConsulterConvontion.setBounds(20, 80, 160, 40);

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(bCancel)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancel)
                        .addGap(78, 78, 78))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(664, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAjouterUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjouterUtilisateurActionPerformed
        this.setVisible(false);
        Employer h = new Employer(id);
        h.setVisible(true);
    }//GEN-LAST:event_bAjouterUtilisateurActionPerformed

    private void bConsulterUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsulterUtilisateurActionPerformed
        this.setVisible(false);
        ConsulterUser h = new ConsulterUser(id);
        h.setVisible(true);
    }//GEN-LAST:event_bConsulterUtilisateurActionPerformed

    private void bAjouterPartenaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjouterPartenaireActionPerformed
        this.setVisible(false);
        partenaire h = new partenaire(id);
        h.setVisible(true);
    }//GEN-LAST:event_bAjouterPartenaireActionPerformed

    private void bConsulterPartenaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsulterPartenaireActionPerformed
        this.setVisible(false);
        ConsulterPartenaire h = new ConsulterPartenaire(id);
        h.setVisible(true);
    }//GEN-LAST:event_bConsulterPartenaireActionPerformed

    private void bAjouterConvontionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjouterConvontionActionPerformed
        this.setVisible(false);
        Convontion h = new Convontion(id);
        h.setVisible(true);
    }//GEN-LAST:event_bAjouterConvontionActionPerformed

    private void bConsulterConvontionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsulterConvontionActionPerformed
        this.setVisible(false);
        ConsulterConvontion h = new ConsulterConvontion(id);
        h.setVisible(true);
    }//GEN-LAST:event_bConsulterConvontionActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
        Cancel();
    }//GEN-LAST:event_bCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parametre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAjouterConvontion;
    private javax.swing.JButton bAjouterPartenaire;
    private javax.swing.JButton bAjouterUtilisateur;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bConsulterConvontion;
    private javax.swing.JButton bConsulterPartenaire;
    private javax.swing.JButton bConsulterUtilisateur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
